### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by jpgenovese-f3** [yusukebe/revealgo#9]
Hi! First of all thank you for this small project. I really like the idea!

I tried to install it using the recommended method, but I get this issue:

```sh
$ go get github.com/yusukebe/revealgo/cmd/revealgo
go: downloading github.com/yusukebe/revealgo v1.0.0
go: downloading github.com/jessevdk/go-flags v1.5.0
../../go/pkg/mod/github.com/yusukebe/revealgo@v1.0.0/server.go:16:12: pattern assets/revealjs: no matching files found
```

My go version is: `go version go1.16.6 linux/amd64`.

Thank you!

**Comment by yusukebe** [comment]
`go get` can't fetch git submodule for reveal.js. So run the commands below

```
$ git clone git@github.com:yusukebe/revealgo.git
$ cd revealgo
$ git submodule update --init --recursive
$ go get
```

Thank you.
